---
- hosts: QA
  become: True
  tasks:
  
   - name: Make sure a service unit is stop
     service:
       name: cloudblm-asset-service
       state: stopped

   - name: Remove the Asset-management directory
     command: "rm -rf /opt/apps/AssetManagementService"
   
   - name: Copy Asset-management file local to remote 
     copy:
       src: /opt/apps/AssetManagementService    
       dest: /opt/apps/

           
   - name: Make sure a service unit is restart
     service:
       name: cloudblm-asset-service
       state: restarted